# Generated by Django 4.2.2 on 2023-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_student_teacher_student_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(related_name="teachers", to="school.teacher"),
        ),
    ]
