# Generated by Django 4.2.2 on 2023-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_alter_student_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(related_name="students", to="school.teacher"),
        ),
    ]
